<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TamaPokeFlasher</AssemblyName>
    <RootNamespace>TamaPoke.Flasher</RootNamespace>
    <ApplicationIcon>assets\TamaPoke.ico</ApplicationIcon>
    <Version>2.2.0</Version>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\TamaPoke.ico" />
    <PackageReference Include="System.IO.Ports" Version="10.0.0" />
    <PackageReference Include="System.Management" Version="10.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="payload\base-*.bin" LogicalName="TamaPoke.Payload.%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
