#pragma once

#include <Arduino.h>

// Decoder for the compact TPA1 files generated by tools/build_audio_assets.py.
// A clip is loaded into PSRAM once, so LittleFS is not touched while sprites
// and audio are being rendered concurrently.
class AdpcmClip {
 public:
  bool load(const char *path);
  void unload();
  void rewind();
  bool next(int16_t *sample);
  bool loaded() const { return blob_ != nullptr; }
  uint32_t sampleCount() const { return sampleCount_; }

 private:
  uint8_t *blob_ = nullptr;
  size_t blobSize_ = 0;
  const uint8_t *payload_ = nullptr;
  uint32_t sampleCount_ = 0;
  uint32_t samplePosition_ = 0;
  int16_t initialPredictor_ = 0;
  uint8_t initialStepIndex_ = 0;
  int32_t predictor_ = 0;
  int16_t stepIndex_ = 0;
};
